# Generated by Django 5.1 on 2024-09-05 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
        ('dietwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='accounts.account'),
        ),
    ]
